version: "3.9"

services:
  db:
    image: khaller/graphdb-free:10.0.0
    ports:
      - 127.0.0.1:7280:7200
    volumes:
      - "./config:/repository.init/cobot:rw"
      - "./data:/repository.init/cobot/toLoad:ro"
      - "./ontology:/ontology:ro"
      - "./db/data:/opt/graphdb/data:rw"
      - "./db/logs:/opt/graphdb/logs:rw"
      - "./db/work:/opt/graphdb/work:rw"
  esm:
    image: semsysess/esm:1.3.0
    environment:
      - SPRING_CONFIG_LOCATION=file:///conf/application.properties
    ports:
      - 8082:8080
    volumes:
      - ./config/esm.properties:/conf/application.properties
      - esm-vol:/data
  esw_compiler:
    image: khaller/esw-hcl-compiler:1.0.0
    command: ["/configuration", "/configuration/bin"]
    volumes:
      - ./config/esw:/configuration
  esw:
    image: semsysess/esw:1.2.7
    environment:
      - SPRING_CONFIG_LOCATION=file:///conf/application.properties
    ports:
      - 9002:9000
    volumes:
      - ./config/esw.properties:/conf/application.properties
      - ./config/esw/bin:/webapp/configuration

volumes:
  esm-vol: {}