version: "3.9"

services:
  db:
    image: khaller/graphdb-free:${GDB_VERSION}
    command: ["--GDB_HEAP_SIZE", "${GDB_HEAP_SIZE}"]
    environment:
      - GDB_USER=1000
    ports:
      - 127.0.0.1:7280:7200
    volumes:
      # repository config
      - "data-vol:/repository.init/cobot:rw"
      - "./config/config.ttl:/repository.init/cobot/config.ttl:ro"
      - "./config/sparql/fts.sparql:/repository.init/cobot/sparql/fts.sparql:ro"
      # instance data
      - "./cobot-ontology/data/pilot-data.ttl:/repository.init/cobot/toLoad/pilot-data.ttl:ro"
      - "./cobot-ontology/data/coboticsworld-cobots.trig:/repository.init/cobot/toLoad/coboticsworld-cobots.trig:ro"
      - "./additional-data/eswc2018_ess.trig:/repository.init/cobot/toLoad/eswc2018_ess.trig:ro"
      - "./additional-data/dbpedia_pattern_documentation.nt:/repository.init/cobot/toLoad/dbpedia_pattern_documentation.nt:ro"
      # ontologies
      - "./cobot-ontology/cobot.ttl:/repository.init/cobot/ontology/star2.ttl:ro"
      - "./additional-ontology/co.rdf:/repository.init/cobot/ontology/co.rdf:ro"
      - "./additional-ontology/star-eswc.owl:/repository.init/cobot/ontology/star-eswc.owl:ro"
      # database data
      - "db-vol:/opt/graphdb/data:rw"
      - "db-vol:/opt/graphdb/logs:rw"
      - "db-vol:/opt/graphdb/work:rw"

volumes:
  data-vol: {}
  db-vol: {}